server:
  port: 8181

spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/user_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format_sql: true